server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
    import:
      - 'classpath:domain-chat-api-${spring.config.activate.on-profile}.yml'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
