server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
    import:
      - 'classpath:domain-space-websocket-${spring.config.activate.on-profile}.yml'

logging:
  level:
    com.tistory.devs0n: DEBUG
